const GET_LEADS = "GET_LEADS";
const DELETE_LEAD = "DELETE_LEAD";
const ADD_LEAD = "ADD_LEAD";
const GET_ERRORS = "GET_ERRORS";
const CREATE_MESSAGES = "CREATE_MESSAGES";

export { GET_LEADS, DELETE_LEAD, ADD_LEAD, GET_ERRORS, CREATE_MESSAGES}
