const GET_LEADS = "GET_LEADS";
const DELETE_LEAD = "DELETE_LEAD";
const ADD_LEAD = "ADD_LEAD";
const GET_ERRORS = "GET_ERRORS";
const CREATE_MESSAGES = "CREATE_MESSAGES";
const USER_LOADING = "USER_LOADING";
const USER_LOADED = "USER_LOADED";
const AUTH_ERROR = "AUTH_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";


export {
REGISTER_SUCCESS, REGISTER_FAIL, GET_LEADS, DELETE_LEAD, ADD_LEAD, GET_ERRORS, CREATE_MESSAGES, USER_LOADING, USER_LOADED, AUTH_ERROR, LOGIN_FAIL, LOGIN_SUCCESS, LOGOUT_SUCCESS }
